FROM quay.io/opendatahub-contrib/workbench-images:cuda-runtime-pytorch-c9s-py311_2023c_latest

RUN pip install pip==22.3.1 setuptools==65.3.0

USER 1001

COPY ./input-data /input-data
COPY requirements-elyra.txt ./
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements-elyra.txt && \
    chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    fix-permissions /opt/app-root -P

RUN python -c 'from sentence_transformers import SentenceTransformer; import os; \
    model = SentenceTransformer('all-MiniLM-L6-v2'); \
    model.save("/input-data/" + 'all-MiniLM-L6-v2'); \ 
    model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2'); \
    model.save("/input-data/" + 'paraphrase-multilingual-MiniLM-L12-v2'); \
    import nltk; \
    nltk.set_proxy("http://proxy.dc4ca.siemens.de:8080"); \
    nltk.download("wordnet", download_dir="/nltk_data")'