FROM quay.io/opendatahub-contrib/workbench-images:cuda-runtime-pytorch-c9s-py311_2023c_latest

RUN pip install pip==22.3.1 setuptools==65.3.0

USER 1001

COPY ./input-data /input-data
COPY requirements-elyra.txt ./
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements-elyra.txt && \
    chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    fix-permissions /opt/app-root -P

RUN python -c 'from sentence_transformers import SentenceTransformer; import os; \
    model_name1 = os.environ["SBERT_MODEL_NAME1"]; \
    model_name2 = os.environ["SBERT_MODEL_NAME2"]; \
    model = SentenceTransformer(model_name1); \
    model.save("/app/input-data/" + model_name1); \ 
    model = SentenceTransformer(model_name2); \
    model.save("/app/input-data/" + model_name2); \
    import nltk; \
    nltk.set_proxy("http://proxy.dc4ca.siemens.de:8080"); \
    nltk.download("wordnet", download_dir="/app/nltk_data")'